version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:...
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: database_name
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      restart: always
      ports:
        - "8080:80"
      environment:
        PMA_HOST: db
        MYSQL_ROOT_PASSWORD: root_password
volumes:
  dbdata:
